export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  nodeEnv: process.env.NODE_ENV ?? "development",
  authProvider: process.env.AUTH_PROVIDER ?? "manus",
  llmProvider: process.env.LLM_PROVIDER ?? "manus",
  llmShadowProvider: process.env.LLM_SHADOW_PROVIDER ?? "",
  storageProvider: process.env.STORAGE_PROVIDER ?? "forge",
  databaseProvider: process.env.DATABASE_PROVIDER ?? "mysql",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  openAiBaseUrl: process.env.OPENAI_BASE_URL ?? "https://api.openai.com/v1",
  anthropicBaseUrl: process.env.ANTHROPIC_BASE_URL ?? "https://api.anthropic.com/v1",
  geminiBaseUrl:
    process.env.GEMINI_BASE_URL ??
    "https://generativelanguage.googleapis.com/v1beta/openai",
  llmModelOpenAi: process.env.LLM_MODEL_OPENAI ?? "gpt-4.1-mini",
  llmModelAnthropic: process.env.LLM_MODEL_ANTHROPIC ?? "claude-3-5-sonnet-latest",
  llmModelGemini: process.env.LLM_MODEL_GEMINI ?? "gemini-2.5-flash",
  llmModelManus: process.env.LLM_MODEL_MANUS ?? "gemini-2.5-flash",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "auto",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3PublicBaseUrl: process.env.S3_PUBLIC_BASE_URL ?? "",
  storageDualWrite: process.env.STORAGE_DUAL_WRITE === "true",
  storageDualReadVerify: process.env.STORAGE_DUAL_READ_VERIFY === "true",
  durableMediaCopy: process.env.STORAGE_DURABLE_MEDIA_COPY === "true",
  authJwtIssuer: process.env.AUTH_JWT_ISSUER ?? "",
  authJwtAudience: process.env.AUTH_JWT_AUDIENCE ?? "",
  authJwksUrl: process.env.AUTH_JWKS_URL ?? "",
  authJwtSecret: process.env.AUTH_JWT_SECRET ?? "",
  webhooksSharedSecret: process.env.WEBHOOKS_SHARED_SECRET ?? "",
  wavespeedApiKey: process.env.WAVESPEED_API_KEY ?? "",
  shotstackApiKey: process.env.SHOTSTACK_API_KEY ?? "",
};
